# Generated by Django 6.0.8 on 2026-09-29 13:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0013_assessmentcalibrationconsent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeDirectionRevision",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("unknown", "Not sure yet"),
                            ("declined", "Connection declined"),
                            ("priority", "Saved priority"),
                            ("outcome", "Intended outcome"),
                        ],
                        max_length=16,
                    ),
                ),
                ("priority_index", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("intended_outcome", models.CharField(blank=True, max_length=500)),
                (
                    "contract_version",
                    models.CharField(default="GG-PRACTICE-DIRECTION-1.0", max_length=40),
                ),
                ("canonical_snapshot", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="growth.assessmentrun"
                    ),
                ),
                (
                    "personal_os",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="growth.personalosrevision",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="growth.practiceprotocol"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("assessment_run_id", "protocol_id", "revision"),
                "base_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment_run", "protocol", "revision"),
                        name="unique_practice_direction_revision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="practice_direction_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ("unknown", "declined", "priority", "outcome"))
                        ),
                        name="practice_direction_known_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("contract_version", "GG-PRACTICE-DIRECTION-1.0")),
                        name="practice_direction_known_version",
                    ),
                ],
            },
        ),
    ]
